name: hynzo
description: Hyperlocal Network Zone.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.1
  pigment: ^1.0.4
  http_interceptor: ^1.0.2
  shared_preferences: ^2.0.8
  animated_text_kit: ^4.2.1
  sms_autofill: ^2.2.0
  flutter_chat_ui: ^1.5.2
  file_picker: ^4.2.5
  uuid: ^3.0.5
  mime: ^1.0.1
  open_file: ^3.2.1
  image_picker: ^0.8.4+4
  timeago: ^3.1.0
  web_socket_channel: ^2.1.0
  flutter_easyloading: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/books.png
    - assets/images/burger.png
    - assets/images/camera.png
    - assets/images/check.png
    - assets/images/compass.png
    - assets/images/blue_circle.png
    - assets/images/game.png
    - assets/images/gym.png
    - assets/images/location.png
    - assets/images/new_user_image_one.png
    - assets/images/new_user_image_two.png
    - assets/images/new_user_image_three.png
    - assets/images/paint.png
    - assets/images/registration.png
    - assets/images/tree.png
    - assets/images/right_white_arrow.png
    - assets/images/mobile.png
    - assets/images/first_button.png
    - assets/images/second_button.png
    - assets/images/third_button.png
    - assets/images/dummy_user_one.png
    - assets/images/dummy_user_two.png
    - assets/images/dummy_user_three.png
    - assets/images/dummy_user_four.png
    - assets/images/dummy_user_five.png
    - assets/images/dummy_user_six.png
    - assets/images/dummy_user_seven.png
    - assets/images/cricket.png
    - assets/images/archery.png
    - assets/images/chess.png
    - assets/images/category_item_five.png
    - assets/images/category_item_four.png
    - assets/images/category_item_one.png
    - assets/images/category_item_six.png
    - assets/images/category_item_three.png
    - assets/images/category_item_two.png
    - assets/images/category_rectangle_five.png
    - assets/images/category_rectangle_four.png
    - assets/images/category_rectangle_one.png
    - assets/images/category_rectangle_six.png
    - assets/images/category_rectangle_three.png
    - assets/images/category_rectangle_two.png
    - assets/images/suggested_one.png
    - assets/images/suggested_two.png
    - assets/images/suggested_three.png
    - assets/images/home_active.png
    - assets/images/home_inactive.png
    - assets/images/game_active.png
    - assets/images/game_inactive.png
    - assets/images/events_active.png
    - assets/images/events_inactive.png
    - assets/images/message_active.png
    - assets/images/message_inactive.png
    - assets/images/more_active.png
    - assets/images/more_inactive.png
    - assets/images/profile_image.png
    - assets/images/profile_image_background.png
    - assets/images/profile_star.png
    - assets/images/help.png
    - assets/images/news.png
    - assets/images/wallet.png
    - assets/images/subscription.png
    - assets/images/edit.png
    - assets/images/about.png
    - assets/images/settings.png
    - assets/images/event_category_five.png
    - assets/images/event_category_four.png
    - assets/images/event_category_three.png
    - assets/images/event_category_two.png
    - assets/images/event_category_one.png
    - assets/images/events_dummy_five.png
    - assets/images/events_dummy_four.png
    - assets/images/events_dummy_three.png
    - assets/images/events_dummy_two.png
    - assets/images/events_dummy_one.png
    - assets/images/black_rectangle.png
    - assets/images/message_image_one.png
    - assets/images/message_image_two.png
    - assets/images/message_image_three.png
    - assets/images/message_image_four.png
    - assets/images/message_image_five.png
    - assets/images/read.png
    - assets/images/news_two.png
    - assets/images/news_one.png
    - assets/images/home_rectangle.png
    - assets/images/chess_home.png
    - assets/images/blue_add.png
    - assets/images/blue_circle_outline.png
    - assets/images/coin.png
    - assets/images/search.png
    - assets/images/right_arrow.png
    - assets/messages.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-SemiBold.otf
    - family : sf_pro_display
      fonts:
        - asset: assets/fonts/sf_pro_display.ttf
    - family : open_sans
      fonts:
          - asset: assets/fonts/open_sans.ttf
