import 'package:flutter/material.dart';
import 'package:flutter_chat_ui/flutter_chat_ui.dart';

class CustomTheme {
  ChatTheme theme = DefaultChatTheme(
    primaryColor: Colors.indigo,
    userNameTextStyle: TextStyle(),
    errorColor: Colors.red,
    inputBorderRadius: BorderRadius.circular(10),
    userAvatarImageBackgroundColor: Colors.white,
    emptyChatPlaceholderTextStyle: TextStyle(),
    sentMessageBodyTextStyle: TextStyle(),
    receivedMessageDocumentIconColor: Colors.black,
    dateDividerTextStyle: TextStyle(),
    messageInsetsHorizontal: 5,
    sentMessageCaptionTextStyle: TextStyle(),
    sendButtonIcon: null,
    receivedMessageBodyTextStyle: TextStyle(),
    inputTextStyle: TextStyle(),
    dateDividerMargin: EdgeInsets.all(1),
    statusIconPadding: EdgeInsets.all(1),
    seenIcon: null,
    userAvatarNameColors: [Colors.indigo, Colors.indigo],
    messageBorderRadius: 5,
    sentMessageLinkDescriptionTextStyle: TextStyle(),
    errorIcon: null,
    receivedMessageLinkTitleTextStyle: TextStyle(),
    inputTextDecoration: InputDecoration.collapsed(hintText: 'type here...'),
    backgroundColor: Colors.white,
    attachmentButtonIcon: null,
    receivedMessageCaptionTextStyle: TextStyle(),
    userAvatarTextStyle: TextStyle(),
    sentMessageDocumentIconColor: Colors.white,
    inputPadding: EdgeInsets.all(1),
    sentMessageLinkTitleTextStyle: TextStyle(),
    messageInsetsVertical: 5,
    inputTextColor: Colors.indigoAccent,
    deliveredIcon: null,
    documentIcon: null,
    sentEmojiMessageTextStyle: TextStyle(),
    secondaryColor: Colors.amber,
    sendingIcon: null,
    receivedEmojiMessageTextStyle: TextStyle(),
    inputBackgroundColor: Colors.white,
    receivedMessageLinkDescriptionTextStyle: TextStyle(),
  );
}
